AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: PonchonetaALB
      Subnets:
        - !ImportValue PonchonetaPublicSubnet1
        - !ImportValue PonchonetaPublicSubnet2
      SecurityGroups:
        - !ImportValue PonchonetaALBSecurityGroup
      Scheme: internet-facing
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: PonchonetaTG
      Port: 3000
      Protocol: HTTP
      VpcId: !ImportValue PonchonetaVPC
      TargetType: instance
      HealthCheckPath: /

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  PonchonetaALBDNS:
    Value: !GetAtt ALB.DNSName
    Export:
      Name: PonchonetaALBDNS

  PonchonetaTargetGroup:
    Value: !Ref TargetGroup
    Export:
      Name: PonchonetaTargetGroup
