AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer para Ponchoneta
Parameters:
  Subnet1:
    Type: String
    Description: Subred pública 1
  Subnet2:
    Type: String
    Description: Subred pública 2
  ALBSecurityGroup:
    Type: String
    Description: Security Group para el ALB

Resources:
  PonchonetaALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: PonchonetaALB
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Scheme: internet-facing
      Type: application

  PonchonetaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: PonchonetaTargetGroup
      Port: 3000
      Protocol: HTTP
      VpcId: !ImportValue PonchonetaVPC
      TargetType: instance
      HealthCheckPath: /health
      Matcher:
        HttpCode: 200

  PonchonetaListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref PonchonetaTargetGroup
      LoadBalancerArn: !Ref PonchonetaALB
      Port: 80
      Protocol: HTTP

Outputs:
  PonchonetaALBDNS:
    Description: DNS público del ALB
    Value: !GetAtt PonchonetaALB.DNSName
    Export:
      Name: PonchonetaALBDNS