AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Auto Scaling con Launch Template

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: PonchonetaLT
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 en us-east-1
        SecurityGroupIds:
          - !ImportValue PonchonetaAppSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
            yum install -y nodejs git mysql
            git clone https://github.com/felipevelasco7/PonchonetaEcommerce.git
            cd PonchonetaEcommerce/backend
            npm install
            node app.js

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue PonchonetaPrivateSubnet
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 1
      TargetGroupARNs:
        - !ImportValue PonchonetaTargetGroup
