AWSTemplateFormatVersion: '2010-09-09'
Description: Auto Scaling Group para instancias EC2 de Ponchoneta
Parameters:
  VPC:
    Type: String
  Subnet1:
    Type: String
  Subnet2:
    Type: String
  AppSecurityGroup:
    Type: String
  TargetGroup:
    Type: String
  DBEndpoint:
    Type: String
Resources:
  PonchonetaLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 para us-east-1
      InstanceType: t3.micro
      SecurityGroups:
        - !Ref AppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          curl -sL https://rpm.nodesource.com/setup_14.x | bash -
          yum install -y nodejs git
          cd /home/ec2-user
          git clone https://github.com/felipevelasco7/PonchonetaEcommerce.git
          cd PonchonetaEcommerce/backend
          sed -i "s/localhost/${DBEndpoint}/g" config/sequelize.js
          npm install
          node app.js &


  PonchonetaAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref Subnet1
        - !Ref Subnet2
      LaunchConfigurationName: !Ref PonchonetaLaunchConfiguration
      MinSize: 1
      MaxSize: 2
      TargetGroupARNs:
        - !Ref TargetGroup

Outputs:
  AutoScalingGroupName:
    Description: Nombre del Auto Scaling Group
    Value: !Ref PonchonetaAutoScalingGroup
    Export:
      Name: PonchonetaAutoScalingGroup