AWSTemplateFormatVersion: '2010-09-09'
Description: Instancia RDS MySQL para la aplicación

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subredes privadas para RDS
      SubnetIds:
        - !ImportValue EcommercePrivateSubnet
        - !ImportValue EcommercePublicSubnet

  EcommerceDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: ecommerce-db
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: 8.0
      MasterUsername: admin
      MasterUserPassword: MySecurePass123!
      VPCSecurityGroups:
        - !ImportValue EcommerceRDSSG
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false

Outputs:
  EcommerceDBEndpoint:
    Value: !GetAtt EcommerceDB.Endpoint.Address
    Export:
      Name: EcommerceDBEndpoint