AWSTemplateFormatVersion: '2010-09-09'
Description: Instancia RDS MySQL para la aplicación Ponchoneta

Resources:
  PonchonetaDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subredes privadas para RDS
      SubnetIds:
        - !ImportValue PonchonetaPrivateSubnet
        - !ImportValue PonchonetaPublicSubnet2  # opcional, pero asegúrate que exista o quítalo

  PonchonetaDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: ponchoneta-db
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: 8.0
      MasterUsername: admin
      MasterUserPassword: MySecurePass123!
      VPCSecurityGroups:
        - !ImportValue PonchonetaRDSSecurityGroup
      DBSubnetGroupName: !Ref PonchonetaDBSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 0

Outputs:
  PonchonetaDBEndpoint:
    Value: !GetAtt PonchonetaDB.Endpoint.Address
    Export:
      Name: PonchonetaDBEndpoint
