AWSTemplateFormatVersion: '2010-09-09'
Description: Grupos de seguridad para Ponchoneta
Parameters:
  VPC:
    Type: String
    Description: VPC donde crear los SG

Resources:
  PonchonetaAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG para las instancias EC2 del backend
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  PonchonetaALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG para el Load Balancer
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  PonchonetaAppSecurityGroup:
    Description: SG para backend
    Value: !Ref PonchonetaAppSecurityGroup
    Export:
      Name: PonchonetaAppSecurityGroup

  PonchonetaALBSecurityGroup:
    Description: SG para Load Balancer
    Value: !Ref PonchonetaALBSecurityGroup
    Export:
      Name: PonchonetaALBSecurityGroup