AWSTemplateFormatVersion: '2010-09-09'
Description: Grupos de seguridad para la aplicación

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir HTTP y SSH
      VpcId: !ImportValue EcommerceVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acceso a RDS desde EC2
      VpcId: !ImportValue EcommerceVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroup

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir tráfico HTTP al ALB
      VpcId: !ImportValue EcommerceVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  EC2SecurityGroup:
    Value: !Ref EC2SecurityGroup
    Export:
      Name: EcommerceEC2SG

  RDSSecurityGroup:
    Value: !Ref RDSSecurityGroup
    Export:
      Name: EcommerceRDSSG

  PonchonetaALBSecurityGroup:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: PonchonetaALBSecurityGroup
