AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups for Ponchoneta App

Resources:

  PonchonetaAppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP (3000) and SSH (22) to EC2
      VpcId: !ImportValue PonchonetaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  PonchonetaRDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow EC2 App to access RDS (MySQL)
      VpcId: !ImportValue PonchonetaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref PonchonetaAppSG

  PonchonetaALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access to ALB (port 80)
      VpcId: !ImportValue PonchonetaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:

  PonchonetaAppSecurityGroup:
    Value: !Ref PonchonetaAppSG
    Export:
      Name: PonchonetaAppSecurityGroup

  PonchonetaRDSSecurityGroup:
    Value: !Ref PonchonetaRDSSG
    Export:
      Name: PonchonetaRDSSecurityGroup

  PonchonetaALBSecurityGroup:
    Value: !Ref PonchonetaALBSG
    Export:
      Name: PonchonetaALBSecurityGroup
