AWSTemplateFormatVersion: '2010-09-09'
Description: Grupos de seguridad para la aplicación Ponchoneta

Resources:
  PonchonetaAppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir HTTP y SSH a EC2
      VpcId: !ImportValue PonchonetaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  PonchonetaRDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acceso a RDS desde EC2
      VpcId: !ImportValue PonchonetaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref PonchonetaAppSG

  PonchonetaALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir tráfico HTTP al ALB
      VpcId: !ImportValue PonchonetaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  PonchonetaAppSecurityGroup:
    Value: !Ref PonchonetaAppSG
    Export:
      Name: PonchonetaAppSecurityGroup

  PonchonetaRDSSecurityGroup:
    Value: !Ref PonchonetaRDSSG
    Export:
      Name: PonchonetaRDSSecurityGroup

  PonchonetaALBSecurityGroup:
    Value: !Ref PonchonetaALBSG
    Export:
      Name: PonchonetaALBSecurityGroup
